def generate_markdown(sector, analysis):
    return f"""
# 📊 Trade Opportunities Report: {sector.title()} (India)

## 🧠 Market Analysis
{analysis}

## 📌 Summary
AI-generated insights for trading opportunities in the {sector} sector.

---
Generated by Trade Opportunities API
"""